### ISSUE TITLE
File Transfer retry is desperately needed

### ISSUE THREAD

**Issue by Lexy2** [3CS-Software/test-out#13]
Sending some 2426 files to server fails 2 out of 3 times with 
```[20:34:58 WRN] [ThreeCS.TestOut.Core.Communication.gPRC.RpcMessageBusClient] Server: error occurred handling ThreeCS.TestOut.Core.Servers.Messages.HostFileTransferMessage from Server
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ChunkedEncodingMessageBody.PumpAsync()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ChunkedEncodingMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)        
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at ThreeCS.TestOut.Core.Communication.FileTransferStreamServer.OnHostFileTransfer(String senderId, HostFileTransferMessage message) in /home/runner/work/test-out/test-out/ThreeCS.TestOut.Core/Servers/FileTransferStreamServer.cs:line 75
   at ThreeCS.TestOut.Core.Communication.gPRC.RpcMessageBusClient.<>c__DisplayClass28_2.<<HandleMessage>b__0>d.MoveNext() in /home/runner/work/test-out/test-out/ThreeCS.TestOut.Core/Communication/gRPC/RpcMessageBusClient.cs:line 285
```

Have you checked OctopusDeploy's [Halibut](https://github.com/OctopusDeploy/Halibut/tree/master)?
Looks promising.

**Comment by mstancombe** [comment]
I think this might be as simple as the default timeout for the http client

**Comment by mstancombe** [comment]
@Lexy2 Default timeout for httpclient is 100 seconds, which is probably the issue.  Have removed this and updated to 0.7.3 beta.  Let me know if it fixes this issue.  

Regarding retries, it is a decent idea and we can put it  on the roadmap, but if this makes the transfers reliable, I'd say it will be pretty far down.

**Comment by mstancombe** [comment]
https://github.com/3CS-Software/test-out/releases/tag/v0.7.3-alpha

**Comment by mstancombe** [comment]
also related: https://github.com/3CS-Software/test-out/issues/5

**Comment by Lexy2** [comment]
Yup seems better now, although tests fail with my test set anyway 😢
